version: '3'
services:
  api:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - .:/src
      - /src/node_modules
    depends_on:
      - elasticsearch
    networks:
      - backend
      - public
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.1
    ports:
      - "9200:9200"
    environment:
      http.host: 0.0.0.0
      transport.host: 127.0.0.1
    volumes:
      - ./tmp/docker/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - backend
  kibana:
    image: docker.elastic.co/kibana/kibana:5.5.1
    ports:
      - "5601:5601"
    environment:
      elasticsearch.url: elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - backend
networks:
  backend:
  public: